/**
 * Cloud District Location Data.
 *
 * Encapsulated locally within features/cloud/ to adhere to architecture rules:
 * components never import directly from data/ or storage/.
 *
 * Step 2 & 3: Structured fictional telemetry, hardware fabric specs,
 * architectural capabilities, and simulated operational metrics.
 */

export const CLOUD_LOCATIONS = [
  {
    id: 'compute',
    code: 'SECTOR // 01-A',
    title: 'Compute Island',
    subtitle: 'Distributed Processing & Virtualized Mesh',
    badge: 'PROCESSING CLUSTER',
    description:
      'A high-throughput floating cluster of elastic compute nodes and virtualized processing cores orchestrating distributed workloads across the cloud continuum.',
    status: 'ACTIVE // NOMINAL',
    statusVariant: 'stable',
    coordinates: 'GRID // 42.10 N · 18.44 E',
    actionConfig: {
      actionId: 'scale-up',
      label: 'SCALE UP',
      activeLabel: 'ORCHESTRATING MESH...',
      completedLabel: 'SCALING COMPLETE',
      maxLabel: 'MAX CLUSTER CAPACITY',
      description: 'Provision +2 elastic container instances to alleviate cluster pressure',
    },
    // Base nominal metrics before operation
    baseMetrics: [
      {
        id: 'cpu-usage',
        label: 'CPU Usage',
        value: '62%',
        percent: 62,
        statusVariant: 'stable',
        type: 'gauge',
      },
      {
        id: 'memory-usage',
        label: 'Memory Usage',
        value: '71%',
        percent: 71,
        statusVariant: 'warning',
        type: 'gauge',
      },
      {
        id: 'active-instances',
        label: 'Active Instances',
        value: '4',
        subValue: 'Cluster nodes online',
        statusVariant: 'stable',
        type: 'counter',
      },
      {
        id: 'request-load',
        label: 'Request Load',
        value: '1,240 req/min',
        subValue: 'Ingress routing normal',
        statusVariant: 'stable',
        type: 'rate',
      },
      {
        id: 'instance-status',
        label: 'Instance Status',
        value: 'ONLINE',
        statusVariant: 'stable',
        type: 'status',
      },
      {
        id: 'scaling-state',
        label: 'Scaling State',
        value: 'STABLE',
        statusVariant: 'stable',
        type: 'status',
      },
    ],
    technicalSpecs: [
      { label: 'Hypervisor Subsystem', value: 'KVM MicroVM / Firecracker' },
      { label: 'Allocated Cores', value: '128 Cores · 256 Threads' },
      { label: 'Workload Isolation', value: 'Hardware-Enforced cgroups v2' },
      { label: 'Fabric Bus Latency', value: '0.42 ms Inter-Core' },
    ],
    telemetry: [
      { label: 'CPU Usage', value: '62%' },
      { label: 'Memory Usage', value: '71%' },
      { label: 'Active Instances', value: '4' },
      { label: 'Request Load', value: '1,240 req/min' },
      { label: 'Instance Status', value: 'ONLINE' },
      { label: 'Scaling State', value: 'STABLE' },
    ],
    features: [
      'Elastic auto-scaling nodes with instant provisioning',
      'Zero-trust container isolation and hardware virtualization',
      'Dynamic workload orchestration across multi-zone regions',
    ],
    iconType: 'compute',
  },
  {
    id: 'storage',
    code: 'SECTOR // 01-B',
    title: 'Storage Valley',
    subtitle: 'Multi-Tier Object & Block Storage Expanse',
    badge: 'STORAGE FABRIC',
    description:
      'An expansive topological valley of tiered persistent volumes, distributed object vaults, and geo-replicated archival blocks designed for zero data loss.',
    status: 'SYNCED // REPLICATED',
    statusVariant: 'stable',
    coordinates: 'GRID // 38.82 N · 24.19 E',
    actionConfig: {
      actionId: 'optimize-storage',
      label: 'OPTIMIZE STORAGE',
      activeLabel: 'COMPACTING VAULTS...',
      completedLabel: 'STORAGE OPTIMIZED',
      maxLabel: 'ZERO UNCLAIMED BLOCKS',
      description: 'Run block-level deduplication and automated cold-tier migration',
    },
    // Base nominal metrics before operation
    baseMetrics: [
      {
        id: 'total-capacity',
        label: 'Total Capacity',
        value: '12 TB',
        subValue: 'Tiered NVMe array',
        statusVariant: 'stable',
        type: 'metric',
      },
      {
        id: 'used-capacity',
        label: 'Used Capacity',
        value: '7.4 TB',
        percent: 61.7,
        subValue: '61.7% utilized',
        statusVariant: 'stable',
        type: 'gauge',
      },
      {
        id: 'available-capacity',
        label: 'Available Capacity',
        value: '4.6 TB',
        percent: 38.3,
        subValue: '38.3% unallocated',
        statusVariant: 'stable',
        type: 'metric',
      },
      {
        id: 'storage-type',
        label: 'Storage Type',
        value: 'OBJECT STORAGE',
        subValue: 'Multi-region bucket mesh',
        statusVariant: 'stable',
        type: 'badge',
      },
      {
        id: 'read-activity',
        label: 'Read Activity',
        value: '840 ops/min',
        subValue: 'Sustained throughput',
        statusVariant: 'stable',
        type: 'rate',
      },
      {
        id: 'write-activity',
        label: 'Write Activity',
        value: '310 ops/min',
        subValue: 'Synchronous commit pool',
        statusVariant: 'stable',
        type: 'rate',
      },
      {
        id: 'storage-status',
        label: 'Storage Status',
        value: 'HEALTHY',
        statusVariant: 'stable',
        type: 'status',
      },
    ],
    technicalSpecs: [
      { label: 'Durability Standard', value: '99.999999999% (11 9s)' },
      { label: 'Tier Topology', value: 'NVMe Hot · Standard Cool · Deep Cold' },
      { label: 'Data Encryption', value: 'AES-256 GCM · Quantum-Ready' },
      { label: 'Geo-Redundancy', value: '3x Cross-Region Autonomous Sync' },
    ],
    telemetry: [
      { label: 'Total Capacity', value: '12 TB' },
      { label: 'Used Capacity', value: '7.4 TB' },
      { label: 'Available Capacity', value: '4.6 TB' },
      { label: 'Storage Type', value: 'OBJECT STORAGE' },
      { label: 'Read Activity', value: '840 ops/min' },
      { label: 'Write Activity', value: '310 ops/min' },
      { label: 'Storage Status', value: 'HEALTHY' },
    ],
    features: [
      'High-durability distributed object storage with instant recall',
      'Continuous block encryption with quantum-resistant key cycles',
      'Automated lifecycle tiering from NVMe cache to cold archive',
    ],
    iconType: 'storage',
  },
  {
    id: 'database',
    code: 'SECTOR // 01-C',
    title: 'Database Lake',
    subtitle: 'High-Concurrency Relational & Vector Reservoir',
    badge: 'DATA RESERVOIR',
    description:
      'A deep digital reservoir maintaining continuous state synchronization, atomic transactional streams, and sub-millisecond query execution across relational and vector domains.',
    status: 'OPTIMIZED // STREAMING',
    statusVariant: 'stable',
    coordinates: 'GRID // 45.67 N · 31.05 E',
    actionConfig: {
      actionId: 'optimize-database',
      label: 'OPTIMIZE DATABASE',
      activeLabel: 'REINDEXING & ANALYZING...',
      completedLabel: 'DATABASE OPTIMIZED',
      maxLabel: 'INDEXES TUNED',
      description: 'Rebuild query plan caches and prune stale connection pool threads',
    },
    // Base nominal metrics before operation
    baseMetrics: [
      {
        id: 'database-engine',
        label: 'Database Engine',
        value: 'CLOUD SQL',
        subValue: 'High-availability cluster',
        statusVariant: 'stable',
        type: 'badge',
      },
      {
        id: 'active-connections',
        label: 'Active Connections',
        value: '128',
        percent: 25.6,
        subValue: '128 / 500 pool limit',
        statusVariant: 'stable',
        type: 'gauge',
      },
      {
        id: 'query-rate',
        label: 'Query Rate',
        value: '2,480 queries/min',
        subValue: '~41.3 QPS sustained',
        statusVariant: 'stable',
        type: 'rate',
      },
      {
        id: 'replication-status',
        label: 'Replication Status',
        value: 'SYNCHRONIZED',
        statusVariant: 'stable',
        type: 'status',
      },
      {
        id: 'storage-usage',
        label: 'Storage Usage',
        value: '68%',
        percent: 68,
        subValue: '340 GB / 500 GB provisioned',
        statusVariant: 'warning',
        type: 'gauge',
      },
      {
        id: 'database-health',
        label: 'Database Health',
        value: 'HEALTHY',
        statusVariant: 'stable',
        type: 'status',
      },
    ],
    technicalSpecs: [
      { label: 'Consensus Subsystem', value: 'Raft-Distributed Multi-Paxos' },
      { label: 'Vector Index', value: 'HNSW Index · 1536 Dimensions' },
      { label: 'Transaction Model', value: 'Strict Serializable (ACID)' },
      { label: 'Replication Drift', value: '< 1.2 ms lag window' },
    ],
    telemetry: [
      { label: 'Database Engine', value: 'CLOUD SQL' },
      { label: 'Active Connections', value: '128' },
      { label: 'Query Rate', value: '2,480 queries/min' },
      { label: 'Replication Status', value: 'SYNCHRONIZED' },
      { label: 'Storage Usage', value: '68%' },
      { label: 'Database Health', value: 'HEALTHY' },
    ],
    features: [
      'Strict serializable ACID transactions with distributed consensus',
      'Integrated high-dimensional vector embeddings for AI indexing',
      'Automatic read-replica sharding and zero-downtime schema evolution',
    ],
    iconType: 'database',
  },
]
