/**
 * Cloud District Incident Simulation Engine.
 *
 * Encapsulated within features/cloud/ to adhere to architectural layering.
 * Provides deterministic incident lifecycle definitions, impact models,
 * response resolution, and score/health effects.
 *
 * Lifecycle:
 * IDLE -> DETECTED -> ACTIVE -> (PLAYER RESPONSE) -> RESOLVED | ESCALATED
 */

export const INCIDENT_LIFECYCLE = {
  IDLE: 'idle',
  DETECTED: 'detected',
  ACTIVE: 'active',
  RESOLVED: 'resolved',
  ESCALATED: 'escalated',
}

export const CLOUD_INCIDENTS = [
  {
    id: 'high-traffic',
    title: 'High Traffic Surge',
    code: 'INC-01 // TRAFFIC_FLOOD',
    targetLocationId: 'compute',
    severity: 'warning',
    description:
      'Sudden request surge across ingress gateways. CPU utilization exceeded 90% and request latency is degrading.',
    impactSummary: 'CPU 94% · Load 4,850 req/min · Cluster Strained',
    correctActionId: 'scale-up',
    correctActionLabel: 'SCALE UP (+2 NODES)',
    incorrectActionId: 'bypass-shedding',
    incorrectActionLabel: 'BYPASS LOAD SHEDDING',
    reward: 5,
    penalty: -10,
    activeMetrics: [
      {
        id: 'cpu-usage',
        label: 'CPU Usage',
        value: '94%',
        percent: 94,
        statusVariant: 'warning',
        type: 'gauge',
        isModified: true,
      },
      {
        id: 'memory-usage',
        label: 'Memory Usage',
        value: '88%',
        percent: 88,
        statusVariant: 'warning',
        type: 'gauge',
        isModified: true,
      },
      {
        id: 'active-instances',
        label: 'Active Instances',
        value: '4',
        subValue: 'Saturated node capacity',
        statusVariant: 'warning',
        type: 'counter',
        isModified: true,
      },
      {
        id: 'request-load',
        label: 'Request Load',
        value: '4,850 req/min',
        subValue: 'Ingress threshold breached',
        statusVariant: 'warning',
        type: 'rate',
        isModified: true,
      },
      {
        id: 'instance-status',
        label: 'Instance Status',
        value: 'OVERLOADED',
        statusVariant: 'warning',
        type: 'status',
        isModified: true,
      },
      {
        id: 'scaling-state',
        label: 'Scaling State',
        value: 'STRAINED // WARNING',
        statusVariant: 'warning',
        type: 'status',
        isModified: true,
      },
    ],
    resolvedMetrics: [
      {
        id: 'cpu-usage',
        label: 'CPU Usage',
        value: '48%',
        percent: 48,
        statusVariant: 'stable',
        type: 'gauge',
        isModified: true,
      },
      {
        id: 'memory-usage',
        label: 'Memory Usage',
        value: '59%',
        percent: 59,
        statusVariant: 'stable',
        type: 'gauge',
        isModified: true,
      },
      {
        id: 'active-instances',
        label: 'Active Instances',
        value: '6',
        subValue: '+2 Nodes Provisioned',
        statusVariant: 'stable',
        type: 'counter',
        isModified: true,
      },
      {
        id: 'request-load',
        label: 'Request Load',
        value: '980 req/min',
        subValue: 'Load balanced across mesh',
        statusVariant: 'stable',
        type: 'rate',
        isModified: true,
      },
      {
        id: 'instance-status',
        label: 'Instance Status',
        value: 'ONLINE',
        statusVariant: 'stable',
        type: 'status',
        isModified: true,
      },
      {
        id: 'scaling-state',
        label: 'Scaling State',
        value: 'STABLE // NOMINAL',
        statusVariant: 'stable',
        type: 'status',
        isModified: true,
      },
    ],
  },
  {
    id: 'server-failure',
    title: 'Instance Node Kernel Panic',
    code: 'INC-02 // CORE_FAULT',
    targetLocationId: 'compute',
    severity: 'critical',
    description:
      'Primary virtual machine hypervisor crashed due to unhandled hardware exception. Server instance is OFFLINE.',
    impactSummary: 'Server OFFLINE · 0 Cores Active · Critical Failure',
    correctActionId: 'restart-server',
    correctActionLabel: 'RESTART SERVER',
    incorrectActionId: 'force-shutdown',
    incorrectActionLabel: 'FORCE POWER OFF',
    reward: 5,
    penalty: -10,
    activeMetrics: [
      {
        id: 'cpu-usage',
        label: 'CPU Usage',
        value: '0%',
        percent: 0,
        statusVariant: 'critical',
        type: 'gauge',
        isModified: true,
      },
      {
        id: 'memory-usage',
        label: 'Memory Usage',
        value: '0%',
        percent: 0,
        statusVariant: 'critical',
        type: 'gauge',
        isModified: true,
      },
      {
        id: 'active-instances',
        label: 'Active Instances',
        value: '0',
        subValue: 'All instances faulted',
        statusVariant: 'critical',
        type: 'counter',
        isModified: true,
      },
      {
        id: 'request-load',
        label: 'Request Load',
        value: '0 req/min',
        subValue: 'No ingress processing',
        statusVariant: 'critical',
        type: 'rate',
        isModified: true,
      },
      {
        id: 'instance-status',
        label: 'Instance Status',
        value: 'OFFLINE',
        statusVariant: 'critical',
        type: 'status',
        isModified: true,
      },
      {
        id: 'scaling-state',
        label: 'Scaling State',
        value: 'FAILOVER REQUIRED',
        statusVariant: 'critical',
        type: 'status',
        isModified: true,
      },
    ],
    resolvedMetrics: [
      {
        id: 'cpu-usage',
        label: 'CPU Usage',
        value: '52%',
        percent: 52,
        statusVariant: 'stable',
        type: 'gauge',
        isModified: true,
      },
      {
        id: 'memory-usage',
        label: 'Memory Usage',
        value: '64%',
        percent: 64,
        statusVariant: 'stable',
        type: 'gauge',
        isModified: true,
      },
      {
        id: 'active-instances',
        label: 'Active Instances',
        value: '4',
        subValue: 'Core services restored',
        statusVariant: 'stable',
        type: 'counter',
        isModified: true,
      },
      {
        id: 'request-load',
        label: 'Request Load',
        value: '1,120 req/min',
        subValue: 'Traffic resumed normally',
        statusVariant: 'stable',
        type: 'rate',
        isModified: true,
      },
      {
        id: 'instance-status',
        label: 'Instance Status',
        value: 'ONLINE',
        statusVariant: 'stable',
        type: 'status',
        isModified: true,
      },
      {
        id: 'scaling-state',
        label: 'Scaling State',
        value: 'RESTARTED // STABLE',
        statusVariant: 'stable',
        type: 'status',
        isModified: true,
      },
    ],
  },
  {
    id: 'storage-capacity',
    title: 'Storage Capacity Exhaustion',
    code: 'INC-03 // VOL_EXHAUST',
    targetLocationId: 'storage',
    severity: 'warning',
    description:
      'Persistent volume array approaching critical ceiling (98% capacity). Automated writes are being throttled.',
    impactSummary: 'Used 11.8 TB / 12 TB · 98% Full · IO Throttled',
    correctActionId: 'optimize-storage',
    correctActionLabel: 'OPTIMIZE STORAGE',
    incorrectActionId: 'disable-write-lock',
    incorrectActionLabel: 'DISABLE WRITE LOCK',
    reward: 5,
    penalty: -10,
    activeMetrics: [
      {
        id: 'total-capacity',
        label: 'Total Capacity',
        value: '12 TB',
        subValue: 'Tiered NVMe array',
        statusVariant: 'stable',
        type: 'metric',
      },
      {
        id: 'used-capacity',
        label: 'Used Capacity',
        value: '11.8 TB',
        percent: 98.3,
        subValue: '98.3% threshold exceeded',
        statusVariant: 'critical',
        type: 'gauge',
        isModified: true,
      },
      {
        id: 'available-capacity',
        label: 'Available Capacity',
        value: '0.2 TB',
        percent: 1.7,
        subValue: 'Critical shortage',
        statusVariant: 'critical',
        type: 'metric',
        isModified: true,
      },
      {
        id: 'storage-type',
        label: 'Storage Type',
        value: 'OBJECT STORAGE',
        subValue: 'Write lock engaged',
        statusVariant: 'warning',
        type: 'badge',
      },
      {
        id: 'read-activity',
        label: 'Read Activity',
        value: '840 ops/min',
        subValue: 'Normal read throughput',
        statusVariant: 'stable',
        type: 'rate',
      },
      {
        id: 'write-activity',
        label: 'Write Activity',
        value: '45 ops/min',
        subValue: 'Severe buffer throttle',
        statusVariant: 'warning',
        type: 'rate',
        isModified: true,
      },
      {
        id: 'storage-status',
        label: 'Storage Status',
        value: 'WARNING // EXHAUSTION',
        statusVariant: 'warning',
        type: 'status',
        isModified: true,
      },
    ],
    resolvedMetrics: [
      {
        id: 'total-capacity',
        label: 'Total Capacity',
        value: '12 TB',
        subValue: 'Tiered NVMe array',
        statusVariant: 'stable',
        type: 'metric',
      },
      {
        id: 'used-capacity',
        label: 'Used Capacity',
        value: '6.8 TB',
        percent: 56.7,
        subValue: '56.7% utilized · 5.0 TB reclaimed',
        statusVariant: 'stable',
        type: 'gauge',
        isModified: true,
      },
      {
        id: 'available-capacity',
        label: 'Available Capacity',
        value: '5.2 TB',
        percent: 43.3,
        subValue: 'Healthy headroom',
        statusVariant: 'stable',
        type: 'metric',
        isModified: true,
      },
      {
        id: 'storage-type',
        label: 'Storage Type',
        value: 'OBJECT STORAGE',
        subValue: 'Multi-region bucket mesh',
        statusVariant: 'stable',
        type: 'badge',
      },
      {
        id: 'read-activity',
        label: 'Read Activity',
        value: '840 ops/min',
        subValue: 'Sustained throughput',
        statusVariant: 'stable',
        type: 'rate',
      },
      {
        id: 'write-activity',
        label: 'Write Activity',
        value: '310 ops/min',
        subValue: 'Throttle disengaged',
        statusVariant: 'stable',
        type: 'rate',
        isModified: true,
      },
      {
        id: 'storage-status',
        label: 'Storage Status',
        value: 'HEALTHY',
        statusVariant: 'stable',
        type: 'status',
        isModified: true,
      },
    ],
  },
]

/** Find incident definition by ID */
export function findIncident(id) {
  return CLOUD_INCIDENTS.find((inc) => inc.id === id) || null
}

/** Check if an action ID resolves the incident correctly */
export function isCorrectIncidentAction(incident, actionId) {
  if (!incident) return false
  return incident.correctActionId === actionId
}
